coverage:
  status:
    patch: off
    project:
      default:
        target: auto # auto will use the coverage from the base commit (pull request base or parent commit) coverage to compare against.
        threshold: 0%
comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]