name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
      with:
        go-version: '1.17.6'
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: collect coverage
      run: make coverage-report
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
      with:
        file: test.html
        token: "${{ secrets.CODECOV_TOKEN }}"