name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
      with:
        go-version: '1.17.6'
    - name: Build
      run: make build
    - name: Run tests
      run: make test-codecov
    - name: Upload coverage reports to Codecov with GitHub Action
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      run: chmod +x codecov ./codecov -t ${CODECOV_TOKEN}